server:
  port: 8099
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/do_an_tot_nghiep
    username: root
    password: 30121998
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
jwt:
  secret: datn